services:
  api:
    build: .
    container_name: customer_segmentation_api
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  dashboard:
    build: .
    container_name: customer_segmentation_dashboard
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app/dashboard.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api
    environment:
      - PYTHONPATH=/app/src
